name: Publish Packages

on:
  workflow_dispatch: {}
    # inputs:
    #   version:
    #     description: 'major | minor | patch'
    #     required: true
    #     default: 'patch'

jobs:
  publish-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Deps
        run: |
          npm ci

      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Packages
        run: |
          npm publish --access restricted
